//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inquizitor2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionComment
    {
        public int QCommentId { get; set; }
        public int QuestionId { get; set; }
        public string Content { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
